### ISSUE TITLE
Dashboard no longer working - needs older bokeh version

### ISSUE THREAD

**Issue by loostrum** [KernelTuner/dashboard#2]
After installing, `ktdashboard -demo tests/test_cache_1000.json ` fails with an error in bokeh:
```
  File "/home/powersensor/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bokeh/core/has_props.py", line 368, in _raise_attribute_error_with_matches
    raise AttributeError(f"unexpected attribute {name!r} to {self.__class__.__name__}, {text} attributes are {nice_join(matches)}")
AttributeError: unexpected attribute 'plot_height' to figure, similar attributes are outer_height, height or min_height
```

This looks like a breaking change in bokeh 3.0: https://stackoverflow.com/questions/74280959/attributeerror-unexpected-attribute-plot-width-to-figure-similar-attributes

If you want to make the dashboard work with bokeh 3.0, I can pick up fixing this.

**Comment by benvanwerkhoven** [comment]
That would be great @loostrum !
